version: '3.7'

services:
  noa-redis:
    image: bitnami/redis:latest
    container_name: noa-redis
    restart: always
    environment:
      - REDIS_PASSWORD=123123
    ports:
      - 6379:6379
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - '80:80'
      - '443:443'
      - '12100-12103:12100-12103'
    volumes:
      - ~/docker-configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/docker-configs/nginx/html:/usr/share/nginx/html
    restart: always
