name: Deploy Node Server

on:
  push:
    branches:
      - master
    paths:
      - 'packages/noa-server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up pnpm
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.x # 指定 pnpm 版本

      - name: Install dependencies and Build
        run: |
          export NOA_CI_TEMP_PATH=$(uuidgen)
          rm pnpm-workspace.yaml
          cd packages/noa-server
          pnpm install --no-frozen-lockfile
          pnpm build
          cp ecosystem.config.js dist/
          mv dist ../../noa-ci

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_DEPLOY_HOST }}
          username: ${{ secrets.SERVER_DEPLOY_USERNAME }}
          password: ${{ secrets.SERVER_DEPLOY_PASSWORD }}
          rm: true
          strip_components: 1
          source: 'noa-ci/*'
          target: /home/noa/tmp/noa-ci

      # Step 6: SSH into server and reload with pm2
      - name: SSH and reload with pm2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_DEPLOY_HOST }}
          username: ${{ secrets.SERVER_DEPLOY_USERNAME }}
          password: ${{ secrets.SERVER_DEPLOY_PASSWORD }}
          script: |
            mkdir -p /home/noa/apps/noa
            cd /home/noa/apps/noa
            find . -maxdepth 1 ! -name 'node_modules' ! -name '.' ! -name '..' -exec rm -rf {} +
            rsync -av /home/noa/tmp/noa-ci/ ./
            pnpm install --no-frozen-lockfile
            pm2 reload ./ecosystem.config.js
